---
title: "Homework 1 - Sara Kramer"
output: github_document
---

```{r}
library(tidyverse)
```

# Problem 1
```{r} 
data("penguins", package = "palmerpenguins")

nrow(penguins)

ncol(penguins)

mean(penguins$flipper_length_mm, na.rm = TRUE)

ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point()

ggsave("penguin_scatter_plot.pdf")
```

# Problem 2
```{r}
samp = rnorm(10)
norm_samp_pos = samp > 0

samp = tibble(
  vec_numeric = 11:20,
  vec_char = c("I", "have", "been", "to", "more", "than", "ten", "countries", "so", "far"),
  vec_logical = c(TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE),
  vec_factor = factor(c("alone", "family", "family", "friends", "alone", "friend", "friends", "alone", "family", "friends"))
)

mean(samp$vec_numeric)

samp %>% 
  pull(vec_char) %>% 
  mean()

samp %>% 
  pull(vec_logical) %>% 
  mean()

samp %>% 
  pull(vec_factor) %>% 
  mean()
```

```{r eval = FALSE}
as.numeric(samp$vec_cha)
as.numeric(samp$vec_logical)
as.numeric(samp$factor)
```

